### ISSUE TITLE
Theme states are not preserved

### ISSUE THREAD

**Issue by shubhamnanche** [WirelessAlien/BhagavadGitaApp#15]
**Description**
When I open the app for the first time after installing it, it opens with the Light Theme as the default theme selected. Although, it is the `Light Theme` that is displayed in the selection, the actual app theme is the one that is selected in the system-wide android theme mode in the android settings, which shouldn't be the case. Let's say I my device theme is "`Dark Theme`" (for android 10+), and I am opening the app for the first time, the app opens in dark mode because of this issue, now I change the app theme to `Dark Theme`, nothing happens as it is already in the dark mode, and I again change it to `Light Theme`, this time the app changes to light theme. Now, I close the app and remove it from the background (recents menu) as well, and I reopen the app, the expected behavior is the app must open in `Light Theme`, but instead it follows the android's system-wide theme mode.

**To Reproduce**
1. Install the app fresh (and keep your android's system theme as dark)
2. Open the app and go to the theme's menu (it shows `Light Theme` as selected)
3. Change the theme to `Dark Theme` and back to `Light Theme`
4. Close the app and remove it from the recents menu
5. Reopen the app and it will show `Light Theme`, although the app is still displaying in dark mode

**Expected behavior**
The app should always be displayed in the theme that is shown as selected in the theme's alert dialog.

**Comment by WirelessAlien** [comment]
I am actually aware about the problems in theme change. To apply only light & dark theme easy but the way black theme was applied was not a great way. I will have to change the theme change method.

**Comment by shubhamnanche** [comment]
Your shared preferences tags are cluttered... Have you tried making a single class holding all the sharedpref tags in one place? That way, you'll get the exact string you need to get their values and it'll be more organised. I am trying to correct the way black, light and dark themes were implemented. Let me see what works well.

**Comment by WirelessAlien** [comment]
> Your shared preferences tags are cluttered... Have you tried making a single class holding all the sharedpref tags in one place?
>
I have not tried only thought about it later (like- If I can manage time maybe I will do it 🙂)
> That way, you'll get the exact string you need to get their values and it'll be more organised.
>
Yeah, that's true.
> I am trying to correct the way black, light and dark themes were implemented. Let me see what works well.
>
👍
