### ISSUE TITLE
Verse 48 translates opens Verse 1.

### ISSUE THREAD

**Issue by sak96** [WirelessAlien/BhagavadGitaApp#3]
https://github.com/WirelessAlien/BhagavadGitaApp/blob/cc48a216ee03178f7a53778332a2273b05d68afb/app/src/main/java/com/wirelessalien/android/bhagavadgita/activity/VerseDetailActivity.kt#L133-L135

this above line uses `verse_number` to open  translation.

But the json has verse number resets for each chapter.
https://github.com/WirelessAlien/BhagavadGitaApp/blob/cc48a216ee03178f7a53778332a2273b05d68afb/app/src/main/assets/verse.json#L566-L577

Thus the translation on verse 48 open verse 1 and not the correct verse. 

so the code should ideally use `verse_order`  instead of `veser_number`.

ps: thanks for the app.

**Comment by WirelessAlien** [comment]
#5 Fixed

**Comment by sak96** [comment]
hi @WirelessAlien do you know which issue is related to packaging of this app to fdroid.
i am not able to find the fdroid packaging update.
i checked here: 
https://gitlab.com/fdroid/rfp/-/issues/?sort=created_date&state=opened&search=gita&first_page_size=10

**Comment by WirelessAlien** [comment]
> hi @WirelessAlien do you know which issue is related to packaging of this app to fdroid. i am not able to find the fdroid packaging update. i checked here: https://gitlab.com/fdroid/rfp/-/issues/?sort=created_date&state=opened&search=gita&first_page_size=10

I don't know, according to [this ](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-exactly-does-the-building-process-work)F-Droid should automatically detect the update within 2 days but it has not done it yet, so maybe I have to manually update the metadata. I have asked them what to do - [Link](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13436#note_1519856961)

**Comment by sak96** [comment]
ok i see a commit happened 19hr ago.
may be will check after a day or two.
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.wirelessalien.android.bhagavadgita.yml?ref_type=heads

**Comment by WirelessAlien** [comment]
> ok i see a commit happened 19hr ago. may be will check after a day or two. https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.wirelessalien.android.bhagavadgita.yml?ref_type=heads

ooh, thanks, I did not see that. There is no issue now, build completed - https://gitlab.com/fdroid/fdroiddata/-/pipelines/974742750
so the the new update will be available soon.

**Comment by sak96** [comment]
looks like the [build failed](https://monitor.f-droid.org/builds/log/com.wirelessalien.android.bhagavadgita/4) for this app.

some mismatch between their build and the binary in releases.

> DOES NOT VERIFY
> ERROR: APK Signature Scheme v2 signer #1: APK integrity check failed. CHUNKED_SHA256 digest mismatch. Expected: <16340ecf97125512ef9310eebc5ec80529c3ca3a98a2f1e2a7ad05f6bc5e5d51>, actual: <948df443324a3bf6110a7f3197ab12c299bc5834cab6a502a6111b91178f9625>
> 2023-08-23 07:55:43,148 ERROR: Could not build app com.wirelessalien.android.bhagavadgita: compared built binary to supplied reference binary but failed

**Comment by WirelessAlien** [comment]
Yeah, it is a reproducible build issue. 

The v3 was not released to solve the fdroid issue, I added new features and  I published it. 

May be we can skip the the version 2.1 and build v3.0 to see if that solves the issue

Let's see what happens 😔

**Comment by sak96** [comment]
Something is wrong for fdroid.
https://monitor.f-droid.org/builds/log/com.wirelessalien.android.bhagavadgita/5#site-footer

**Comment by WirelessAlien** [comment]
> Something is wrong for fdroid.
> https://monitor.f-droid.org/builds/log/com.wirelessalien.android.bhagavadgita/5#site-footer
> 

The issue is solved now but rebuild has not started, it will.

See this - https://github.com/WirelessAlien/BhagavadGitaApp/issues/8
