### ISSUE TITLE
Font size increase and text copyiing capability

### ISSUE THREAD

**Issue by guleriaakshit** [WirelessAlien/BhagavadGitaApp#9]
Hi Abhilash,

First, I want to thank you for creating this app, I am a Hindu, so it is much appreciated.  I waned to ask you if you can add two features to the app. Firstly, I want that a person can increase the font size as I wanted my mom to have the app, but she can't see that small of a text. And another feature I want is the ability to copy text from anywhere in the app, so that I can share it to anyone anywhere.

Warm regards,
Akshit Guleria

**Comment by WirelessAlien** [comment]
Thank you for your appreciation, and both of the features you mentioned will be implemented.

**Comment by guleriaakshit** [comment]
> Thank you for your appreciation, and both of the features you mentioned will be implemented.

Thanks, and when can I expect new version to roll out?

**Comment by WirelessAlien** [comment]
> Thanks, and when can I expect new version to roll out?

Since I have exam from the 12th to the 15th, I will begin working on it after the exam is over so maybe about 10 days.

**Comment by guleriaakshit** [comment]
> 
> > Thanks, and when can I expect new version to roll out?
> 
> Since I have exam from the 12th to the 15th, I will begin working on it after the exam is over so maybe about 10 days.

Nice, I'll be waiting eagerly. 😊💖

**Comment by WirelessAlien** [comment]
I released a new version. You may download from [Release](https://github.com/WirelessAlien/BhagavadGitaApp/releases) or you can wait to download from fdroid. It will take 5-7 days to get publish on fdroid 👍

**Comment by guleriaakshit** [comment]
> I released a new version. You may download from [Release](https://github.com/WirelessAlien/BhagavadGitaApp/releases) or you can wait to download from fdroid. It will take 5-7 days to get publish on fdroid 👍

Thanks man, I really appreciate it. :)
